### PR TITLE
[WIP] Developer Documentation - the beginning #117

### PR DESCRIPTION
**Pull request by oneolddev**
This is my initial effort regarding the addition of more developer focused documentation #117.
- *docs* folder add to root of repository
- *docs* folders added for *2wr-app*, *admin* and *api*
- initial documentation effort has started
- added *Two Weeks Ready* overview diagram

I'm looking for feedback 😃.  
- I am assuming that the audience for these documents will be primarily intermediate to senior developers. Is that reasonable?

### CODE REVIEW

**Comment by dpaquette** [comment]
Great start here @c0g1t8 . I think your assumptions regarding the audience is reasonable. We might also want to add some "More Info" links to external documentation for more junior folks. There is some talk about on-boarding junior contributors as well.

**Comment by c0g1t8** [comment]
@dpaquette 

From what I can tell, **Auth0** is a hard dependency. There is no _mock/fake_ that we can run locally for development and testing purpooses.  Am I correct?  If so, other than enhancing the overview information, should documenting **Auth0** be the next priority?

**Comment by dpaquette** [comment]
Yes, Auth0 is a hard dependency. This is easy enough for the App and API since we can provide the client id and issuer details in the sample config files. Unfortunately this is a bit more difficult in the context of the admin app since it requires a client secret  which we won't want to share.. It also requires an Auth0 admin to grant someone the admin role. We will need to review that to see if we can make onboarding easier.

**Comment by dpaquette** [comment]
@c0g1t8  did you need anything else from the team to proceed with this work?

**Pull request closed without merging**
