### PR TITLE
First start of Family Plans

### PR DESCRIPTION
**Pull request by shawnwildermuth**
First pass at beginning screens of the Family Plans. Create and view should work.

### CODE REVIEW

**Comment by schuback** [comment]
Thank you Shawn for helping us out on this project!

**Comment by shawnwildermuth** [comment]
I assume that this will be merged by @codingbandit, am I right?

**Comment by schuback** [comment]
Yes @shawnwildermuth - @codingbandit will do the merge and stuff.  I am more on the emergency management side of the house.

**Comment by codingbandit** [comment]
Thank you!!

**Comment by shawnwildermuth** [comment]
I'll have a new PR every few days. Re-thinking some of the code already.

**Pull request merged**
