### PR TITLE
Include DevContainer for Development Environment

### PR DESCRIPTION
**Pull request by davidwesst**
Relates to #124 

## Task List
- [x] Install Dotnet, Azure Functions, and Node dependencies into environment
- [x] Get api to `dotnet build`
- [x] Get 2wr-app to `npm build`
- [x] Install and Setup dotnet 5.0 SDK
- [x] Playwright Tests cannot open chormium browser (i.e. tests fail)
- [x] `dotnet restore` needs to be run mutliple times to success (possible network issue with Nuget)
- [x] Include and run CosmosDB emulator
- [ ] ~~Need the gh-cli tool installed too~~

## Development Notes
- Tested on Windows 10 with Docker for Windows, Codespaces, and Pop_OS 21.01 with Docker
- Using Node 16.13.1 (LTS) which appears to be running fine, even though it uses Node 14 (LTS-1) in the build (this can be changed, if necessary)
- Initial setup works as expected and runs build and tests of projects using scripts added in `tools` directory
- CosmoDB in Docker emulator scripts work on Windows consistently, in Linux if run one at a time by user, and _NOT_ in codespaces.
   - Still provides a pretty good experience for anyone using devcontainers on their local machine and works in Codespaces, but will likely need to setup an Azure-hosted development instance (as recommended in current documentation)
- Removed the feature for GitHub CLI, as it's not really necessary and was behaving strangely.

### CODE REVIEW

**Comment by davidwesst** [comment]
Playwright options
- Fluxbox https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md
- Desktop X Forward (probably won't work with Codespaces) https://blog.jongallant.com/2021/08/playwright-codegen-devcontainer/

**Comment by davidwesst** [comment]
CosmosDB Emulator setup https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21

**Comment by davidwesst** [comment]
Maybe update the `dockerfile` to just install the sdks on image build using apt.

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2110-

**Comment by davidwesst** [comment]
@dpaquette -- When you have a moment, take a peek and we can schedule a code review or something. 😊

**Comment by dpaquette** [comment]
@davidwesst  This looks great. Thanks for your contribution!  I was able to spin up a codespace and get working on the app relatively easily. 

We'll have to think through how that auth works when working in Codespaces.  Let's schedule a time to walk through this together so we can capture the whole "new dev" experience and fill in any of the blanks that are needed. This will go a long way to improve our onboarding documentation.

**Comment by davidwesst** [comment]
Sounds good to me. Glad I could be of some help. 😊

**Comment by davidwesst** [comment]
Post code review items that should be addressed:

- [ ] Create local.settings.json file for the `api` project
- [ ] Create a .env file for the '2wr-app` project
- [ ] Get the emulator working
- [ ] Document a walkthrough of the development environment: 
    - Build all applications
    - Run all application
    - Debug (i.e. hit breakpoint) in all applications

**Comment by davidwesst** [comment]
Tested against Linux (Pop_OS/Ubuntu), Windows 10, and Codespaces. Works consitently with Docker for Desktop on Linux, Windows. May still have minor issues with Codespaces, but may be related to size (i.e. CPU/RAM allocated Codespace).

Documentation not completed, but can follow-up with a document + video on how to use this (along with some further triage on Codespaces issue if that works).

**Review by dpaquette — APPROVED** [review]

**Pull request merged**
