### PR TITLE
Add loding icon to emergency kit list page

### PR DESCRIPTION
**Pull request by neelmallepally**
#58 
-  Added loading icon when the network is slow.
- Added loading text prop to v-data-iterator. It will be shown to user instead of "No Data Available"

### CODE REVIEW

**Comment by shawnwildermuth** [comment]
Please see the global Vuex object that already does this for the entire app. See how I use it in the Family Plans.

**Comment by neelmallepally** [comment]
@shawnwildermuth , thank you for the feedback. Globally adding "Loading.." icon is great idea. I found how you used in the Family Plans page. I'm going to submit a new pull request. How can I abandon this PR?

**Comment by dpaquette** [comment]
@neelmallepally you can just close it here with a comment

**Comment by neelmallepally** [comment]
Abandoning this PR and will submit new PR with Shawn suggestion.

**Pull request closed without merging**
